### ISSUE TITLE
Should print URL when booting

### ISSUE THREAD

**Issue by topfunky** [jlong/serve#107]
On Mac OS X and other OSes, URLs in the terminal can be right clicked and opened in the browser.

Serve would be more useful if it printed the URL that it's serving on after it boots. For example:

    Serving at http://localhost:4000

**Comment by wazery** [comment]
I think their is no need for a PR, I can open the link on with my OS X Terminal with these shortcuts:

**Before OS X Lion:**

`cmd+shift+double-click` on a URL in Terminal.app and it will open in the default program.

**OSX Lion:**

`cmd+double-click` (otherwise you will enter fullscreen mode).

**Comment by topfunky** [comment]
@wazery I believe the issue was that `serve` originally did not print any URL at all, so there was nothing that could be single clicked, double clicked, cmd+shift+triple-clicked with your right foot in and your right foot out, or any other way.

**Comment by wazery** [comment]
Good that they added URLs, so this issue can be closed now, right?

**Comment by topfunky** [comment]
I just tried with 1.5.2 and there's still no URL.

```
Install Mongrel or Thin for better performance.
[2015-04-02 18:28:36] INFO  WEBrick 1.3.1
[2015-04-02 18:28:36] INFO  ruby 2.0.0 (2014-05-08) [universal.x86_64-darwin13]
[2015-04-02 18:28:36] INFO  WEBrick::HTTPServer#start: pid=60526 port=4000
^C[2015-04-02 18:29:08] INFO  going to shutdown ...
[2015-04-02 18:29:08] INFO  WEBrick::HTTPServer#start done.
```

**Comment by wazery** [comment]
Oh, then I will create a PR and reference this issue.

**Comment by wazery** [comment]
Reading in the [lib/serve/application.rb](https://github.com/jlong/serve/blob/master/lib/serve/application.rb#L277) file I found both #277 and #288 lines are printing the URL for only Thin or Mongrell servers. in your log you are using WEBrick, so I am thinking of adding a URL to it also, @jlong WDYTH?

**Comment by jlong** [comment]
Merged! Thank you! This will be in the next release.

**Comment by wazery** [comment]
Cool, thanks.

**Comment by jlong** [comment]
Also made you a contributor. If there is anything else you'd like to tidy up, please do!

**Comment by wazery** [comment]
Awesome, thanks for that, I will investigate in the issues and contribute more :smiley:
