### ISSUE TITLE
Gem not found when trying to install

### ISSUE THREAD

**Issue by geuis** [jlong/serve#125]
gem install serve
    Could not find a valid gem 'serve' (>= 0), here is why:
    Unable to download data from https://rubygems.org/ - no such name (https://rubygems.org/latest_specs.4.8.gz)

**Comment by wazery** [comment]
I can't reproduce on my side, I just installed ti from RubyGems with now problems, please check if it is still reproducible.

**Comment by geuis** [comment]
Its now showing and installing without needing to take further action.
