### ISSUE TITLE
Can't get Serve to work on OS X Yosemite

### ISSUE THREAD

**Issue by dawie** [jlong/serve#129]
$ ruby -v
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
$ gem -v
2.0.14
$ serve
/Library/Ruby/Gems/2.0.0/gems/serve-2.0.0/lib/serve/handlers/dynamic_handler.rb:8:in `extensions': undefined method `mappings' for Tilt:Module (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/serve-2.0.0/lib/serve/handlers/dynamic_handler.rb:15:in `<class:DynamicHandler>'
	from /Library/Ruby/Gems/2.0.0/gems/serve-2.0.0/lib/serve/handlers/dynamic_handler.rb:4:in `<module:Serve>'
	from /Library/Ruby/Gems/2.0.0/gems/serve-2.0.0/lib/serve/handlers/dynamic_handler.rb:3:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/serve-2.0.0/lib/serve.rb:14:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/serve-1.5.2/bin/serve:13:in `<top (required)>'
	from /usr/bin/serve:23:in `load'
	from /usr/bin/serve:23:in `<main>'

**Comment by wazery** [comment]
Please use version 1.5.2

`gem install serve -v 1.5.2`

**Comment by ethancane** [comment]
Same issue for me too. Installing older version for the time being.

**Comment by StaceyOrton1966** [comment]
Same thing here
