### ISSUE TITLE
Serve stopped working... here is the stacktrace

### ISSUE THREAD

**Issue by CaliLuke** [jlong/serve#93]
/Library/Ruby/Gems/1.8/gems/bundler-1.2.4/lib/bundler/rubygems_integration.rb:187:in `stub_source_index170': uninitialized constant Gem::SourceIndex (NameError)
	from /Library/Ruby/Gems/1.8/gems/bundler-1.2.4/lib/bundler/rubygems_integration.rb:353:in `stub_rubygems'
	from /Library/Ruby/Gems/1.8/gems/bundler-1.2.4/lib/bundler/rubygems_integration.rb:250:in `replace_entrypoints'
	from /Library/Ruby/Gems/1.8/gems/bundler-1.2.4/lib/bundler/runtime.rb:14:in `setup'
	from /Library/Ruby/Gems/1.8/gems/bundler-1.2.4/lib/bundler.rb:123:in `setup'
	from /Users/lucacandela/Documents/hack/mmxheader/config.ru:7
	from /Library/Ruby/Gems/1.8/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
	from /Library/Ruby/Gems/1.8/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
	from /Users/lucacandela/Documents/hack/mmxheader/config.ru:0:in `new'
	from /Users/lucacandela/Documents/hack/mmxheader/config.ru:0

**Comment by wazery** [comment]
I think this issue should be marked as stale, it has no comments since a lot of time, also it seems that @CaliLuke fixed the issue.

Please @CaliLuke if the issue is still there tell us, or if you fixed it please mention how you did that.
